name: Distribution
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]

jobs:
  upload-package:
    name: "Build & upload package"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.repository == 'sprockets/sprockets-statsd'
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7  # use 3.7 for wheel compatibility
      - name: Install builder
        run: |
          python -m pip install --upgrade build pip setuptools twine
      - name: Build distributions
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Upload packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true  # just in case...
